id: P004355
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG9299
  title: སླེ་ལུང་བཞད་པའི་རྡོ་རྗེའི་གསུང་རྩོམ་སྐོར་གྱི་ཟིན་ཐོ།
  author: ''
  volumes:
    b1adc2cb6c354b10a833e969c24435ff:
      image_group_id: I1KG9388
      title: ''
      volume_number: 1
      total_pages: 148
      base_file: v001.txt
