id: I689CC1D5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T04:08:42+00:00'
last_modified: '2022-06-07T22:15:00.990135+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9299
  title: སླེ་ལུང་བཞད་པའི་རྡོ་རྗེའི་གསུང་རྩོམ་སྐོར་གྱི་ཟིན་ཐོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedByTbrc
  restrictedInChina: false
  base:
    49E7:
      image_group_id: I1KG9388
      title: ''
      total_pages: 148
      order: 1
      base_file: 49E7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
